# Generated by Django 5.2.8 on 2025-12-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Autre')], default='other', help_text='Prestataire de paiement utilisé.', max_length=20)),
                ('transaction_id', models.CharField(help_text="Identifiant retourné par l'API du prestataire.", max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du paiement.', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Devise du paiement (ISO 4217).', max_length=10)),
                ('status', models.CharField(default='pending', help_text='Statut du paiement (pending, completed, failed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Commande associée à ce paiement, si connue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
