# Generated by ChatGPT to add B2B verification and address book models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        # Ajout du champ is_b2b_verified sur l'utilisateur custom
        migrations.AddField(
            model_name="user",
            name="is_b2b_verified",
            field=models.BooleanField(
                default=False,
                verbose_name="Compte B2B vérifié",
            ),
        ),
        # Création du modèle Address pour le carnet d'adresses
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        verbose_name="Entreprise", max_length=255, blank=True, default=""
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        verbose_name="Nom du contact", max_length=255, blank=True, default=""
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        verbose_name="Adresse", max_length=255
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        verbose_name="Complément", max_length=255, blank=True, default=""
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        verbose_name="Ville", max_length=100
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        verbose_name="Code postal", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        verbose_name="Pays", max_length=100, default="France"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        verbose_name="Téléphone", max_length=50, blank=True, default=""
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        verbose_name="Type",
                        max_length=20,
                        choices=[
                            ("HQ", "Siège"),
                            ("Warehouse", "Entrepôt"),
                            ("Store", "Magasin"),
                            ("Other", "Autre"),
                        ],
                        default="HQ",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Par défaut"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "adresse",
                "verbose_name_plural": "adresses",
                "ordering": ["user", "-is_default"],
            },
        ),
    ]