# Generated by Django 5.2.5 on 2025-10-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_email_change_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchangerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
