# Generated by Django 5.2.8 on 2025-12-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_add_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Identifiant client utilisé pour les promotions catalogue ciblées.', max_length=30, null=True, unique=True, verbose_name='Numéro client'),
        ),
    ]
