# Generated by Django 3.2.25 on 2025-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BamyTest', help_text='Nom public affiché dans la barre de navigation et le pied de page.', max_length=100, verbose_name="Nom de l'entreprise")),
                ('tagline', models.CharField(blank=True, help_text="Brève description ou tagline de l'entreprise.", max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise affiché dans le header.", null=True, upload_to='branding/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#0905f5', help_text='Couleur principale utilisée dans le thème (hexadécimale).', max_length=7, verbose_name='Couleur primaire')),
                ('accent_color', models.CharField(default='#D4AF37', help_text="Couleur d'accent pour les boutons et liens (hexadécimale).", max_length=7, verbose_name="Couleur d'accent")),
                ('dark_color', models.CharField(default='#2D2D2D', help_text="Couleur sombre pour l'arrière-plan (hexadécimale).", max_length=7, verbose_name='Couleur sombre')),
                ('light_color', models.CharField(default='#F8F9FA', help_text='Couleur claire pour les surfaces et le texte (hexadécimale).', max_length=7, verbose_name='Couleur claire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'configuration du site',
                'verbose_name_plural': 'configurations du site',
            },
        ),
    ]
