# Generated by Django 5.2.8 on 2025-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(help_text='Valeur hexadécimale (#RRGGBB) de la couleur primaire', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(help_text='Valeur hexadécimale (#RRGGBB) de la couleur secondaire', max_length=7, verbose_name='Couleur secondaire')),
                ('font_url', models.URLField(blank=True, help_text="URL d'importation d'une police personnalisée (ex\xa0: Google Fonts)", verbose_name='URL de la police')),
                ('logo', models.ImageField(help_text='Fichier image du logo à afficher dans la navigation', upload_to='branding/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(help_text="Icône de favori pour l'onglet du navigateur", upload_to='branding/favicons/', verbose_name='Favicon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'configuration du branding',
                'verbose_name_plural': 'configurations du branding',
            },
        ),
    ]
