# Generated by Django 5.2.8 on 2025-11-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brandingconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandingconfig',
            options={'verbose_name': 'configuration de la marque', 'verbose_name_plural': 'configurations de la marque'},
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text="Icône utilisée dans l'onglet du navigateur", null=True, upload_to='branding/favicons/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='font_url',
            field=models.URLField(blank=True, help_text='Lien vers la police personnalisée à charger (Google Fonts par ex.)', null=True, verbose_name='URL de la police'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de la marque utilisé dans l'interface", null=True, upload_to='branding/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='primary_color',
            field=models.CharField(help_text='Couleur principale du thème (hexadécimal)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='secondary_color',
            field=models.CharField(help_text='Couleur secondaire du thème (hexadécimal)', max_length=7, verbose_name='Couleur secondaire'),
        ),
    ]
