# Generated by Django 5.2.8 on 2025-12-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('settings_currency', models.CharField(default='EUR', help_text='Code ISO de la devise par défaut pour ce client.', max_length=10)),
                ('default_pricing_mode', models.CharField(default='public', help_text='Mode de tarification par défaut (public, b2b, promotion, etc.).', max_length=32)),
                ('allowed_features', models.JSONField(blank=True, default=list, help_text="Liste de fonctionnalités activées pour ce client (ex: 'quotes', 'promotions').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(blank=True, help_text='Représentant commercial assigné à ce client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserClientLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Membre'), ('read_only', 'Lecture seule')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'link utilisateur‑client',
                'verbose_name_plural': 'liens utilisateur‑client',
                'unique_together': {('user', 'client')},
            },
        ),
    ]
