# Generated by Django 5.2.8 on 2025-12-04 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=5, verbose_name='Code postal')),
                ('client_type', models.CharField(choices=[('B2C', 'Particulier'), ('B2B', 'Professionnel'), ('Prospect', 'Prospect'), ('Other', 'Autre')], default='B2C', max_length=20, verbose_name='Type de client')),
                ('store_type', models.CharField(choices=[('Retail', 'Petite distribution'), ('Specialty', 'Magasin spécialisé'), ('Franchise', 'Franchise'), ('Distributor', 'Grande distribution'), ('Wholesale', 'Grossiste'), ('Other', 'Autre')], default='Retail', max_length=50, verbose_name='Type de magasin')),
                ('client_code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Code client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('items', models.TextField(verbose_name='Références et quantités')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
