# Generated by Django 5.2.5 on 2025-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Numéro client'),
        ),
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.CharField(choices=[('B2C', 'Particulier'), ('B2B', 'Professionnel'), ('Prospect', 'Prospect'), ('Other', 'Autre')], default='B2C', max_length=20, verbose_name='Type de client'),
        ),
    ]
