# Generated by Django 5.2.5 on 2025-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_client_number_customer_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_type',
            field=models.CharField(choices=[('Retail', 'Petite distribution'), ('Specialty', 'Magasin spécialisé'), ('Franchise', 'Franchise'), ('Distrubutor ', 'Grande distribution'), ('Wholesale', 'Grossiste'), ('Other', 'Autre')], default='Retail', max_length=50, verbose_name='Type de magasin'),
        ),
    ]
