# Generated by Django 5.2.5 on 2025-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='client_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='client_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Code client'),
        ),
    ]
