# Generated by Django 5.2.8 on 2025-12-05 02:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Référence')),
                ('article_code', models.CharField(help_text="Identifiant unique du produit fourni par le grossiste. Nous autorisons désormais jusqu'à 32\xa0caractères pour couvrir les cas où la référence fournisseur dépasse 7 caractères.", max_length=32, unique=True, verbose_name='Code article')),
                ('ean', models.CharField(blank=True, help_text='Code-barres international du produit.', max_length=14, null=True, verbose_name='EAN')),
                ('pcb_code', models.CharField(blank=True, help_text='Référence constructeur (PCB) pour le produit.', max_length=64, null=True, verbose_name='Code PCB')),
                ('short_description', models.CharField(blank=True, default='', max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_wholesaler', models.DecimalField(blank=True, decimal_places=2, help_text="Tarif appliqué aux clients de type grossiste s'il est renseigné.", max_digits=10, null=True, verbose_name='Prix grossiste')),
                ('price_big_retail', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif appliqué aux clients de type grande distribution (hypermarchés).', max_digits=10, null=True, verbose_name='Prix grande distribution')),
                ('price_small_retail', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif appliqué aux clients de type petite distribution ou commerce de proximité.', max_digits=10, null=True, verbose_name='Prix petite distribution')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit', models.CharField(blank=True, default='', help_text='Unité de conditionnement (ex. carton de 6)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_order_qty', models.PositiveIntegerField(default=10, help_text='Quantité minimale par commande (MOQ).')),
                ('pcb_qty', models.PositiveIntegerField(default=1, help_text='Quantité par PCB (lot/colis).')),
                ('order_in_packs', models.BooleanField(default=False, help_text='Si vrai, commande uniquement par multiples de PCB.')),
                ('is_week_selection', models.BooleanField(default=False, help_text='Produit sélectionné de la semaine')),
                ('selection_start', models.DateField(blank=True, null=True)),
                ('selection_end', models.DateField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_client_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_customer_numbers', models.JSONField(blank=True, default=list, help_text='Liste des numéros clients autorisés pour cette promo.')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.promocatalog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_price'], name='catalog_pro_discoun_fa1b52_idx'),
        ),
    ]
