# Generated by Django 5.2.5 on 2025-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='brands/covers/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        # Sous les versions de Django antérieures à 4.2, l'argument `condition`
        # n'est pas accepté par CheckConstraint.  On utilise donc l'argument
        # `check` et l'opérateur « | » pour exprimer l'OR logique entre deux
        # prédicats : le champ `logo` est nul OU le champ `cover` est nul.  Si
        # les deux sont non nuls, la contrainte est violée.
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(
                check=models.Q(logo__isnull=True) | models.Q(cover__isnull=True),
                name='brand_logo_or_cover_not_both'
            ),
        ),
    ]
