# Generated by Django 5.2.5 on 2025-08-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_cover_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='brand',
            name='brand_logo_or_cover_not_both',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='cover',
        ),
    ]
