# Generated by Django 5.2.5 on 2025-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=10, help_text='Quantité minimale par commande (MOQ).'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_in_packs',
            field=models.BooleanField(default=False, help_text='Si vrai, commande uniquement par multiples de PCB.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pcb_qty',
            field=models.PositiveIntegerField(default=1, help_text='Quantité par PCB (lot/colis).'),
        ),
    ]
