# Generated by Django 5.2.5 on 2025-08-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_code',
            field=models.CharField(help_text='Identifiant unique du produit fourni par le grossiste.', max_length=5, unique=True, verbose_name='Code article'),
        ),
    ]
