# Generated by Django 5.2.5 on 2025-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_code',
            field=models.CharField(help_text='Identifiant unique du produit fourni par le grossiste.', max_length=7, unique=True, verbose_name='Code article'),
        ),
    ]
