# Generated by Django 5.2.5 on 2025-09-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_code',
            field=models.CharField(
                verbose_name='Code article',
                max_length=32,
                unique=True,
                help_text=(
                    'Identifiant unique du produit fourni par le grossiste. '
                    "Nous autorisons désormais jusqu'à 32 caractères pour couvrir les cas "
                    "où la référence fournisseur dépasse 7 caractères."
                ),
            ),
        ),
    ]
