# Generated by ChatGPT to add unit and selection-of-the-week fields on products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_article_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                max_length=100,
                blank=True,
                default="",
                help_text="Unité de conditionnement (ex. carton de 6)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_week_selection",
            field=models.BooleanField(
                default=False,
                help_text="Produit sélectionné de la semaine",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="selection_start",
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="selection_end",
            field=models.DateField(null=True, blank=True),
        ),
    ]