# Generated by Django 5.2.5 on 2025-10-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_add_unit_and_week_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_code',
            field=models.CharField(help_text="Identifiant unique du produit fourni par le grossiste. Nous autorisons désormais jusqu'à 32\xa0caractères pour couvrir les cas où la référence fournisseur dépasse 7 caractères.", max_length=32, unique=True, verbose_name='Code article'),
        ),
    ]
