# Generated by Django 5.2.8 on 2025-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_promocatalog_promoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoitem',
            name='allowed_customer_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Liste des numéros clients autorisés pour cette promo.'),
        ),
    ]
